# Generated by Django 3.2.25 on 2024-07-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='oblast_okrug_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='srid',
            field=models.CharField(max_length=128, verbose_name='Уникальный идентификатор заказа'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='oblast_okrug_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='srid',
            field=models.CharField(max_length=128, verbose_name='Уникальный идентификатор заказа'),
        ),
    ]
