# Generated by Django 3.2.25 on 2024-07-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240703_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_article', models.CharField(max_length=128, verbose_name='Артикул продавца')),
                ('nm_id', models.IntegerField(verbose_name='Артикул WB')),
                ('barcode', models.CharField(max_length=128, verbose_name='Баркод')),
                ('actual_count', models.IntegerField(verbose_name='В наличии')),
                ('sale_count', models.IntegerField(verbose_name='Продано сегодня')),
            ],
            options={
                'verbose_name': 'Отчет производства',
                'verbose_name_plural': 'Отчет производства',
                'db_table': 'sales_report',
            },
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Продажа/возврат', 'verbose_name_plural': 'Продажи и возвраты'},
        ),
    ]
